# Clase 01: Python Fundamentals y Pandas

Primera sesion del curso, enfocada en tomar una base practica de Python para trabajar con datos.

**Objetivos de la sesion**
- repasar sintaxis base de Python
- practicar operaciones, listas, diccionarios e indexing
- usar control de flujo y funciones
- introducir `numpy`
- trabajar con `pandas` sobre un dataset real

**Dataset de la clase**
- Kaggle original: `Supermarket Sales`
- Fuente original: <https://www.kaggle.com/datasets/aungpyaeap/supermarket-sales>
- Mirror CSV para clase: <https://raw.githubusercontent.com/vnaumq/supermarket_sales/main/supermarket_sales.csv>

In [36]:
variable = 1
print(variable)

1

## 0. Setup rapido

Si algo falta, instala paquetes con:

```bash
py -m pip install jupyterlab notebook ipykernel pandas numpy matplotlib seaborn requests beautifulsoup4 lxml openpyxl python-dotenv
```

En VS Code:
- selecciona `Python: Select Interpreter`
- usa `cmd` como terminal por defecto en Windows
- abre este notebook con la extension de `Jupyter`

## Importaciones

Primero cargamos las librerias con las que vamos a trabajar durante la sesion.

In [21]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 50)
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

## 1. Operaciones y sintaxis base

Python permite partir con ideas muy simples: calcular, guardar valores en variables y consultar estructuras de datos.

### Operaciones basicas

- `+` suma
- `-` resta
- `*` multiplicacion
- `/` division
- `%` modulo o residuo

El operador `%` es util, por ejemplo, para detectar si un numero es par o impar.

In [44]:
a = 15
b = 19

In [46]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)

34
-4
285
0.7894736842105263
15

### Variables y tipos

Una variable es un nombre al que le asignamos un valor.

Tipos basicos que aparecen muy seguido:
- `int`: enteros
- `float`: decimales
- `str`: texto
- `bool`: verdadero o falso

13

In [54]:
precio = 12.5
nombre = 'manzana'
activo = True

type(activo)
type(nombre)

str

### Listas e indexing

Una lista guarda varios elementos en orden.

Ideas clave:
- el indexing parte en `0`
- `[-1]` devuelve el ultimo elemento
- un slice como `[1:3]` incluye el inicio y excluye el final

In [24]:
frutas = ['pera', 'uva', 'manzana', 'platano']

print(frutas[0])
print(frutas[-1])
print(frutas[1:3])

pera
platano
['uva', 'manzana']

### Diccionarios

Un diccionario organiza informacion como pares `clave: valor`.

Es util cuando queremos guardar atributos de un mismo objeto, por ejemplo:
- nombre
- categoria
- precio

In [25]:
producto = {
    'nombre': 'cafe',
    'categoria': 'alimentos',
    'precio': 4.5
}

print(producto['nombre'])
print(producto['precio'])

cafe
4.5

### Ejercicio corto

1. Define dos numeros.
2. Calcula suma, resta, division y modulo.
3. Crea una lista con 5 numeros.
4. Imprime el primero y el ultimo.
5. Crea un diccionario con `pais`, `anio` e `inflacion`.
6. Imprime solo `inflacion`.

In [ ]:
# Escribe aqui tu solucion

## 2. Control de flujo

Control de flujo significa decidir y repetir.

Las dos herramientas minimas son:
- `if / else` para tomar decisiones
- `for` para recorrer elementos
- `list comprehensions` para construir listas de forma compacta

### Condicionales

Un condicional evalua si una condicion es verdadera o falsa y ejecuta un bloque segun el resultado.

In [26]:
edad = 20

if edad >= 18:
    print('mayor de edad')
else:
    print('menor de edad')

mayor de edad

### Loops

Un `for` recorre una secuencia elemento por elemento.

In [27]:
numeros = [1, 2, 3, 4, 5]

for n in numeros:
    print(n * 2)

2
4
6
8
10

### List comprehensions

Una list comprehension permite crear una nueva lista en una sola linea.

Sirve muy bien para transformaciones simples y filtros cortos.

In [30]:
pares = [n for n in numeros if n % 2 == 0]
print(pares)

pares_2 = []
for n in numeros:
    if n % 2 == 0:
        pares_2.append(n)
print(pares_2)

[2, 4]
[2, 4]

### Ejercicio corto

Crea una lista de salarios y:

1. imprime `alto` si el salario es mayor o igual a `1200`
2. imprime `bajo` en caso contrario
3. crea una nueva lista solo con salarios mayores o iguales a `1200`

In [ ]:
# Escribe aqui tu solucion

## 3. Funciones

Una funcion recibe entradas, ejecuta una tarea y devuelve un resultado.

La estructura general es:
- `def` para definir
- argumentos de entrada
- codigo interno
- `return` para devolver una salida

In [32]:
def porcentaje_cambio(valor_inicial, valor_final):
    cambio = (valor_final - valor_inicial) / valor_inicial * 100
    return cambio

porcentaje_cambio(100, 120)

20.0

### Idea clave

Una buena funcion encapsula una tarea concreta y se puede reutilizar muchas veces.

### Ejercicio corto

Crea una funcion llamada `precio_con_descuento` que reciba:
- `precio`
- `descuento`

y devuelva el precio final.

In [ ]:
# Escribe aqui tu solucion

## 4. NumPy basico

`NumPy` trabaja con arreglos numericos.

La idea de este bloque no es profundizar, sino introducir una estructura pensada para calculo numerico y operaciones vectorizadas.

In [35]:
x = np.array([10, 20, 30, 40])

print(x)
print(x * 2)
print(x.mean())
print(x.shape)

[10 20 30 40]
[20 40 60 80]
25.0
(4,)

### Idea clave

Con `NumPy` podemos operar sobre arreglos completos sin escribir un loop explicito para cada calculo simple.

### Ejercicio corto

1. Crea un array con 5 numeros.
2. Calcula su promedio.
3. Multiplica todos los valores por `1.1`.

In [ ]:
# Escribe aqui tu solucion

## 5. Pandas: cargar e inspeccionar datos

Ahora pasamos al bloque principal de la clase.

`pandas` sirve para trabajar con datos tabulares. Su estructura central es el `DataFrame`, que podemos pensar como una tabla con filas y columnas.

La primera tarea siempre es leer e inspeccionar el dataset.

### Cargar datos

La celda siguiente intenta cargar el CSV desde un mirror publico. Si prefieres una copia local, guarda el archivo como `data/supermarket_sales.csv` y cambia la ruta.

In [37]:
url = 'https://raw.githubusercontent.com/vnaumq/supermarket_sales/main/supermarket_sales.csv'


df = pd.read_csv(url)

df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.14,548.97,1/5/2019,13:08,Ewallet,522.83,4.76,26.14,9.10
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.82,80.22,3/8/2019,10:29,Cash,76.40,4.76,3.82,9.60
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.22,340.53,3/3/2019,13:23,Credit card,324.31,4.76,16.22,7.40
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.29,489.05,1/27/2019,20:33,Ewallet,465.76,4.76,23.29,8.40
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.21,634.38,2/8/2019,10:37,Ewallet,604.17,4.76,30.21,5.30

### Que mirar al principio

- `head()` para ver las primeras filas
- `shape` para conocer dimensiones
- `columns` para revisar nombres de columnas
- `dtypes` para entender tipos de datos

In [49]:
print(df.shape)
print(df.columns.tolist())

(1000, 17)
['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date', 'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income', 'Rating']

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

## 6. Seleccion de columnas

Seleccionar columnas significa quedarnos solo con las variables que nos interesan para una pregunta concreta.

### Una columna

Una sola columna se puede seleccionar con `df['columna']`.

In [51]:
df['Total'].head()

0   548.97
1    80.22
2   340.53
3   489.05
4   634.38
Name: Total, dtype: float64

### Varias columnas

Varias columnas se seleccionan con una lista: `df[['col1', 'col2']]`.

In [52]:
df[['City', 'Product line', 'Total']].head()

        City            Product line  Total
0     Yangon       Health and beauty 548.97
1  Naypyitaw  Electronic accessories  80.22
2     Yangon      Home and lifestyle 340.53
3     Yangon       Health and beauty 489.05
4     Yangon       Sports and travel 634.38

### Ejercicio corto

Selecciona estas columnas:
- `Branch`
- `City`
- `Customer type`
- `Total`

In [ ]:
# Escribe aqui tu solucion

## 7. Filtros

Filtrar filas significa quedarnos solo con observaciones que cumplen una condicion.

Primero construimos una condicion booleana. Despues la usamos dentro de `df[...]`.

### Filtro simple por categoria

In [53]:
df[df['City'] == 'Yangon'].head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.14,548.97,1/5/2019,13:08,Ewallet,522.83,4.76,26.14,9.10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.22,340.53,3/3/2019,13:23,Credit card,324.31,4.76,16.22,7.40
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.29,489.05,1/27/2019,20:33,Ewallet,465.76,4.76,23.29,8.40
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.21,634.38,2/8/2019,10:37,Ewallet,604.17,4.76,30.21,5.30
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.65,433.69,2/25/2019,14:36,Ewallet,413.04,4.76,20.65,5.80

### Filtro simple por valor numerico

In [55]:
df[df['Total'] > 300].head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.14,548.97,1/5/2019,13:08,Ewallet,522.83,4.76,26.14,9.10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.22,340.53,3/3/2019,13:23,Credit card,324.31,4.76,16.22,7.40
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.29,489.05,1/27/2019,20:33,Ewallet,465.76,4.76,23.29,8.40
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.21,634.38,2/8/2019,10:37,Ewallet,604.17,4.76,30.21,5.30
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.89,627.62,3/25/2019,18:30,Ewallet,597.73,4.76,29.89,4.10

### Filtro con multiples condiciones

- `&` combina condiciones con "y"
- `|` combina condiciones con "o"
- cada condicion debe ir entre parentesis cuando se combinan varias

In [57]:
filtro = (df['City'] == 'Yangon') & (df['Payment'] == 'Cash')
df[filtro].head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
14,829-34-3910,A,Yangon,Normal,Female,Health and beauty,71.38,10,35.69,749.49,3/29/2019,19:21,Cash,713.80,4.76,35.69,5.70
29,848-62-7243,A,Yangon,Normal,Male,Health and beauty,24.89,9,11.20,235.21,3/15/2019,15:36,Cash,224.01,4.76,11.20,7.40
51,162-48-8011,A,Yangon,Member,Female,Food and beverages,44.59,5,11.15,234.10,2/10/2019,15:10,Cash,222.95,4.76,11.15,8.50
56,106-35-6779,A,Yangon,Member,Male,Home and lifestyle,44.34,2,4.43,93.11,3/27/2019,11:26,Cash,88.68,4.76,4.43,5.80
58,817-48-8732,A,Yangon,Member,Female,Home and lifestyle,72.35,10,36.17,759.67,1/20/2019,15:55,Cash,723.50,4.76,36.17,5.40

### Ejercicio corto

Filtra:
1. ventas de `Mandalay`
2. compras con `Ewallet`
3. observaciones donde `Total > 500`
4. observaciones de `Female` en `Health and beauty`

In [ ]:
# Escribe aqui tu solucion

## 8. Groupby y agregaciones

Este es uno de los conceptos mas importantes de la sesion.

`groupby` permite dividir la tabla por categorias y luego resumir cada grupo con una metrica como promedio, suma o conteo.

### Promedio por ciudad

In [62]:
df.groupby('City')
df.groupby('City')['Total'].mean()
df.groupby('City')['Total'].mean().sort_values(ascending=False)

City
Naypyitaw   337.10
Mandalay    319.87
Yangon      312.35
Name: Total, dtype: float64

### Suma por linea de producto

In [63]:
df.groupby('Product line')['Total'].sum().sort_values(ascending=False)

Product line
Food and beverages       56,144.84
Sports and travel        55,122.83
Electronic accessories   54,337.53
Fashion accessories      54,305.89
Home and lifestyle       53,861.91
Health and beauty        49,193.74
Name: Total, dtype: float64

### Promedio por tipo de cliente

In [64]:
df.groupby('Customer type')[['Total', 'gross income']].mean()

               Total  gross income
Customer type
Member        327.79         15.61
Normal        318.12         15.15

### Groupby con mas de una variable

La estructura mental es:
1. agrupar
2. elegir variable
3. resumir

In [ ]:
df.groupby(['City', 'Payment'])['Total'].mean()

City       Payment
Mandalay   Cash          321.27
           Credit card   342.61
           Ewallet       296.58
Naypyitaw  Cash          347.47
           Credit card   309.46
           Ewallet       350.52
Yangon     Cash          307.10
           Credit card   318.22
           Ewallet       312.10
Name: Total, dtype: float64

Reset index se utiliza para poder pasarlo a formato tabla y poder almacenarlo en una variable.

In [70]:
resumen = (
    df.groupby(['City', 'Payment'])['Total']
      .mean()
      .reset_index()
)
resumen.head(10)

        City      Payment  Total
0   Mandalay         Cash 321.27
1   Mandalay  Credit card 342.61
2   Mandalay      Ewallet 296.58
3  Naypyitaw         Cash 347.47
4  Naypyitaw  Credit card 309.46
5  Naypyitaw      Ewallet 350.52
6     Yangon         Cash 307.10
7     Yangon  Credit card 318.22
8     Yangon      Ewallet 312.10

## 8.1 Merge: juntar tablas

Muchas veces la informacion no viene en una sola tabla. `merge` permite combinar dos bases usando una columna en comun.

La estructura mental es:
1. definir la llave comun
2. elegir que tabla va a la izquierda y cual va a la derecha
3. decidir la logica del cruce con `how`

In [ ]:
clientes = pd.DataFrame({
    'cliente_id': [1, 2, 3, 4],
    'cliente': ['Ana', 'Bastian', 'Carla', 'Diego'],
    'ciudad': ['Santiago', 'Valparaiso', 'Concepcion', 'La Serena']
})

compras = pd.DataFrame({
    'cliente_id': [1, 1, 2, 5],
    'producto': ['Cafe', 'Te', 'Jugo', 'Agua'],
    'monto': [3500, 2800, 4100, 1900]
})

display(clientes)
display(compras)

La llave comun es `cliente_id`.

- `inner`: deja solo coincidencias en ambas tablas
- `left`: deja todo lo de la tabla izquierda y completa lo que encuentre en la derecha
- `right`: deja todo lo de la tabla derecha y completa lo que encuentre en la izquierda
- `outer`: deja todo lo de ambas tablas, aunque no tengan match

In [ ]:
merge_inner = compras.merge(clientes, on='cliente_id', how='inner')
merge_left = compras.merge(clientes, on='cliente_id', how='left')
merge_right = compras.merge(clientes, on='cliente_id', how='right')
merge_outer = compras.merge(clientes, on='cliente_id', how='outer', indicator=True)

print('INNER: solo ids presentes en ambas tablas')
display(merge_inner)

print('LEFT: conserva todas las filas de compras')
display(merge_left)

print('RIGHT: conserva todas las filas de clientes')
display(merge_right)

print('OUTER: conserva todo y muestra de donde viene cada fila')
display(merge_outer)

### Preguntas de negocio

Responde con `pandas`:

1. ¿Que ciudad tiene mayor venta promedio?
2. ¿Que linea de producto genera mayor venta total?
3. ¿Miembros y no miembros gastan distinto en promedio?
4. ¿Que metodo de pago aparece mas?
5. ¿Que categoria tiene mejor rating promedio?

In [ ]:
# Escribe aqui tu solucion

## 9. Mini desafio

Construye una tabla resumen por `Product line` con:
- numero de transacciones
- venta total
- venta promedio
- rating promedio

Ordena la tabla por `venta total` de mayor a menor.

In [ ]:
# Escribe aqui tu solucion

## 10. Cierre

Ideas que deberian quedar de esta clase:

- Python permite escribir operaciones, estructuras y funciones de forma clara
- las listas y diccionarios son estructuras basicas muy utiles
- `if`, `for` y funciones permiten controlar logica y reutilizar codigo
- `numpy` introduce arreglos numericos y operaciones vectorizadas
- `pandas` es la herramienta central para leer, filtrar, agrupar y resumir datos tabulares